import useOrderHistoryStore from "../orders/orderHistoryStore";
import formatCurrency from "../utils/formatCurrency";

function Dashboard() {
  const orders = useOrderHistoryStore((state) => state.orders);

  const totalOrders = orders.length;

  const pendingOrders = orders.filter(
    (order) => order.status === "Pending",
  ).length;

  const totalRevenue = orders.reduce(
    (total, order) => total + Number(order.total || 0),
    0,
  );

  const menuCount = 12;

  // Calculate total revenue generated by each dish
  const sales = {};

  orders.forEach((order) => {
    order.items.forEach((item) => {
      if (!sales[item.id]) {
        sales[item.id] = {
          id: item.id,
          name: item.name,
          revenue: 0,
        };
      }

      sales[item.id].revenue += Number(item.price) * item.quantity;
    });
  });

  // Get the five dishes that generated the most revenue
  const topSellingDishes = Object.values(sales)
    .sort((a, b) => b.revenue - a.revenue)
    .slice(0, 5);

  const maxRevenue =
    topSellingDishes.length > 0 ? topSellingDishes[0].revenue : 0;

  return (
    <div className="admin-dashboard">
      <h1>Admin Dashboard</h1>

      <p>Welcome to the Addis Eats admin dashboard.</p>

      <div className="dashboard-cards">
        <div className="dashboard-card">
          <h2>Menu</h2>
          <p>{menuCount}</p>
          <span>Menu items</span>
        </div>

        <div className="dashboard-card">
          <h2>Orders</h2>
          <p>{totalOrders}</p>
          <span>Total orders</span>
        </div>

        <div className="dashboard-card">
          <h2>Pending</h2>
          <p>{pendingOrders}</p>
          <span>Orders waiting</span>
        </div>

        <div className="dashboard-card">
          <h2>Revenue</h2>
          <p>{formatCurrency(totalRevenue)}</p>
          <span>Total order value</span>
        </div>
      </div>

      <section className="sales-chart">
        <h2>Top-Selling Dishes</h2>

        {topSellingDishes.length === 0 ? (
          <p>No sales data yet.</p>
        ) : (
          <div className="sales-list">
            {topSellingDishes.map((dish) => (
              <div className="sales-item" key={dish.id}>
                <div className="sales-info">
                  <span>{dish.name}</span>

                  <strong>{formatCurrency(dish.revenue)}</strong>
                </div>

                <div className="sales-bar">
                  <div
                    className="sales-bar-fill"
                    style={{
                      width: `${(dish.revenue / maxRevenue) * 100}%`,
                    }}
                  ></div>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

export default Dashboard;
